### ISSUE TITLE
Missing images

### ISSUE THREAD

**Issue by jlcs-es** [AztecProtocol/specification#3]
The `Contract Interactions` section is missing two images (GitHub 404's the URLs):

* `![user-to-validator](https://github.com/CreditMint/wiki/blob/master/userToValidator.png?raw=true)`

  ![user-to-validator](https://github.com/CreditMint/wiki/blob/master/userToValidator.png?raw=true)  

* `![zk-dapp-flow](https://github.com/CreditMint/wiki/blob/master/zkDappFlow2.png?raw=true)`

  ![zk-dapp-flow](https://github.com/CreditMint/wiki/blob/master/zkDappFlow2.png?raw=true)  

https://github.com/CreditMint also 404's, is it private or deleted?

**Comment by thomas-waite** [comment]
Thanks for raising this @jlcs-es , I'll get the image location URLs updated today and do a sweep to correct any others. The CreditMint repo no longer exists

**Comment by thomas-waite** [comment]
All updated now :)
