### ISSUE TITLE
Incorrect data length

### ISSUE THREAD

**Issue by borysyuk** [AztecProtocol/specification#4]
Hi, gays
You have incorrect data length in documentation :
https://github.com/AztecProtocol/specification/blob/master/README.md#L94

`
0x40 | 0x60 | noteHash | bytes32 | Hash of the note's elliptic curve points: gamma and sigma
`

You have to change `0x60` to `0x20`
Thanks!

**Comment by thomas-waite** [comment]
Thanks for raising this @borysyuk , you're correct. A PR was recently submitted by @siburu (https://github.com/AztecProtocol/specification/pull/5), so I'll merge that to fix and close the issue.
